# Generated by Django 5.1.3 on 2024-12-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo2', '0002_answer_modify_date_question_modify_date'),
        ('pybo2', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
    ]
