# Generated by Django 5.1.3 on 2024-12-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo2', '0006_merge_20241205_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
    ]
